### ISSUE TITLE
Cenários Testes da Classe Vector Contas

### ISSUE THREAD

**Issue by priscilarfr** [TPII20152/SB06#22]

**Comment by WagnerFrancalino** [comment]
Cenário de Teste: Popular o vector de contas, este caso de teste tem o objetivo de testar as inserções no vector de contas e verificar se o mesmo esta sendo populado.

**Comment by lincolnrocha** [comment]
@priscilarfr essa tarefa foi finalizada? se sim informe o commit que a finaliza!

**Comment by WagnerFrancalino** [comment]
@lincolnrocha  ainda não finalizada, tive problemas para construção do teste, tentando resolver.

**Comment by priscilarfr** [comment]
@lincolnrocha a tarefa finalizada foi a #18 e não esta. A #18 foi decomposta em outras 3 issues, no qual essa é uma delas e por isso foi referenciada no commit.
