### ISSUE TITLE
Versão errada do Sistema Bancário

### ISSUE THREAD

**Issue by lincolnrocha** [TPII20152/SB06#5]
@RafaelSilvaAlbuquerque a versão do Sistema Bancário que você colocou sob controle de versão no repositório está errada. Você deveria ter subido a versão que está disponível na aula cujo tópico no SIGAA começa com "Oficina de Programação II...".

**Comment by RafaelSilvaAlbuquerque** [comment]
resolvido

**Comment by lincolnrocha** [comment]
Sempre que você fizer commit de alguma coisa, ponha na mensagem do commit o número da issue, assim o GitHub associa o commit à issue. Exemplo: "Resolvido #5"
